Implement mute stream with simple tests
opentok/OpenTok-PHP-SDK pull request #292
Opened 2021-10-11 07:38 UTC by SecondeJK

This PR provides functionality for the forceMute feature added to the API.

Link to JIRA ticket:
https://jira.vonage.com/browse/DEVX-5444

## Description
Contains basic tests for typehints and a stock 200 response. The live response from the API is unknown at this point and will be emulated as soon as it is available. Two new methods have been added to both the OpenTok developer facing interface (or more accurate client wrapper) and the underlying guzzle client wrapper.

## Motivation and Context
Ongoing development to roll out new API features, this feature is GA.

## How Has This Been Tested?
Three new tests have been added to the two new methods, the full test suite has been run to pass.

## Example Output or Screenshots (if appropriate):

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-11-02 06:24 UTC, jeffswartz requested changes

2021-11-02 06:24 UTC, jeffswartz commented on src/OpenTok/OpenTok.php
> +    public function muteStreamInSession(string $sessionId, string $streamId): bool
This does not match the proposed API (`OpenTok.forceMuteStream()`. See https://github.com/opentok/api-review/tree/master/mute-all-api.

2021-11-02 06:24 UTC, jeffswartz commented on src/OpenTok/OpenTok.php
> +    public function muteStreamsInSession(string $sessionId, array $excludeStreams): bool
This does not match the proposed API (`OpenTok.forceMuteAll()`. See https://github.com/opentok/api-review/tree/master/mute-all-api.

2021-11-11 09:54 UTC, SecondeJK commented
@jeffswartz The requested changes have been made but I can't resolve it - is this something you can do?

2021-11-23 21:43 UTC, jeffswartz submitted a review, later dismissed

2021-12-01 15:07 UTC, superchilled requested changes
Mostly looks good, though I think one of the the property names in the data payload for `forceMuteAll` is incorrect.

2021-12-01 15:07 UTC, superchilled commented on src/OpenTok/OpenTok.php
> +     *
The property name for the `POST` data expected by the [API endpoint](https://tokbox.com/developer/rest/#force_mute_session) is `excludedStreams`, not `excludedStreamIds`.

2021-12-01 15:07 UTC, superchilled commented on src/OpenTok/Util/Validators.php
> +                self::validateStreamId($streamId);
The property name for the `POST` data expected by the [API endpoint](https://tokbox.com/developer/rest/#force_mute_session) is `excludedStreams`, not `excludedStreamIds`.

2021-12-13 22:48 UTC, jeffswartz submitted a review, later dismissed

2022-02-03 06:16 UTC, jeffswartz approved these changes

2022-02-03 09:42 UTC, superchilled approved these changes

2022-02-03 10:40 UTC, merged