observeForceMute attribute is not returned by the /call endpoint
opentok/OpenTok-PHP-SDK pull request #309
Opened 2022-06-29 15:58 UTC by rGaillard

## Description

The /call endpoint don't return anything about the observeForceMute parameter, eg of response:

array (
  'id' => '',
  'projectId' => '',
  'sessionId' => '',
  'connectionId' => '',
  'streamId' => '',
  'createdAt' => 1656512547785,
  'updatedAt' => 1656512547785,
)  

I also tried the /dial endpoint (the right one according to your documentation: https://tokbox.com/developer/rest/#sip_call) but the result is the same. But maybe the issue is on your API that don't expose this attribute yet.

## Motivation and Context
We can't use the latest version of your SDK right now.

## How Has This Been Tested?

## Example Output or Screenshots (if appropriate):

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [] All new and existing tests passed.

2022-07-26 12:26 UTC, SecondeJK commented
This cannot be merged until the unit tests are fixed.
Can we remove the `observeForceMute` key from the `dialForceMute` mock response, and remove the assertion
in `OpenTokTest.php:2169`.? Then we should be good to go, thanks!

2022-07-26 12:45 UTC, SecondeJK commented
Oh in addition to deleting the array key in `dialForceMute`, it needs to be removed in `dial` as well.

2022-07-27 08:26 UTC, SecondeJK requested changes
Changes needed in comments to fix the test suite

2022-07-27 15:49 UTC, rGaillard commented
@SecondeJK sure, i just made a new commit to update the tests cases. Thank you.

2022-09-05 09:00 UTC, SecondeJK approved these changes

2022-09-05 09:04 UTC, SecondeJK commented
Sorry can you pull in the latest main into your fork and push? We need the test suite to fire, and it's out of date.

2022-10-14 09:46 UTC, rGaillard commented
@SecondeJK sry for delay. I just rebased my PR.

2022-10-26 08:52 UTC, rGaillard commented
I updated the mocks with valid json... Tests are passing now.

2022-10-28 09:02 UTC, SecondeJK commented
I'm unable to merge because this introduces a slight increase in test coverage holes. If you're able to look into finding some testable code to keep codecov happy, that would be good

2022-11-16 11:24 UTC, SecondeJK commented
I've fixed the required codecoverage in #322 which will be merged in. Thank you for your contribution!

2022-11-16 11:24 UTC, closed without merging