HD Resolutions for Broadcast / Archive
opentok/OpenTok-PHP-SDK pull request #313
Opened 2022-09-05 15:27 UTC by SecondeJK

## Description
The Archive and Broadcast API endpoints now support HD resolutions. This PR adds documentation to support these options and a new validator to throw exceptions when unsupported resolutions are given as arguments before they hit the API.

## How Has This Been Tested?
New tests added for the validation

## Example Output or Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-09-26 13:07 UTC, jeffswartz approved these changes
Let's be sure to rev the version (to 4.12.0), before merging the dev branch into main.

2022-09-26 13:13 UTC, jeffswartz requested changes

2022-09-27 13:44 UTC, pardel commented
> Let's be sure to rev the version (to 4.12.0), before merging the dev branch into main.

@jeffswartz we'll up the version once all PRs are being merged.

2022-09-29 01:24 UTC, jeffswartz approved these changes

2022-09-29 11:18 UTC, merged