Feature/multiple archive support
opentok/OpenTok-PHP-SDK pull request #314
Opened 2022-09-09 09:25 UTC by SecondeJK

This documents the ability to pass in a Multi Archive tag into the methods that start an Archive or a Broadcast.

## Description
This is mostly documentation.

## Motivation and Context
Missing feature that is live.

## How Has This Been Tested?
Two new tests added to make sure that adding custom options do not throw exceptions.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-09-26 20:07 UTC, jeffswartz requested changes
The Archive class should include a `multiArchiveTag` property. And the Broadcast class should include a `multiBroadcastTag` property.

2022-09-29 01:24 UTC, jeffswartz requested changes

2022-09-29 01:24 UTC, jeffswartz commented on src/OpenTok/Broadcast.php
> +*
This should be `multiBroadcastTag`

2022-09-29 01:24 UTC, jeffswartz commented on src/OpenTok/Broadcast.php
> +    private $multiArchiveTag;
Broadcast, not archive. (Same comment for the rest of this file.)

2022-10-12 03:51 UTC, jeffswartz requested changes

2022-10-12 03:51 UTC, jeffswartz commented on src/OpenTok/Broadcast.php
> +* See https://tokbox.com/developer/guides/archiving/#simultaneous-archives for more information.
This should be  https://tokbox.com/developer/guides/broadcast/live-streaming/#simultaneous-broadcasts.

2022-10-26 08:37 UTC, pardel approved these changes

2022-10-26 08:39 UTC, merged