Add end-to-end encryption when creating session.
opentok/OpenTok-PHP-SDK pull request #327
Opened 2023-02-21 12:49 UTC by SecondeJK

This PR adds the end to end encryption flag when starting an OpenTok Session.

## Description
See the docs for more context:
https://tokbox.com/developer/guides/end-to-end-encryption/

## Motivation and Context
New features being rolled into our SDKs

## How Has This Been Tested?
Added new test and modified existing one to make sure defaults are read properly.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-02-21 23:47 UTC, jeffswartz commented on src/OpenTok/OpenTok.php
> +    *    OpenTok session.</code>.</li>
```suggestion
    *    <li><code>'e2ee'</code> (Boolean) &mdash; Whether to enable
    *    <a href="https://tokbox.com/developer/guides/end-to-end-encryption">end-to-end encryption</a>
    *    for the OpenTok session.</li>
```

2023-02-21 23:50 UTC, jeffswartz commented on src/OpenTok/Session.php
> +     * @return mixed
Should this be `@return bool`? And can we please add a description:

```suggestion
    /**
     * Whether <a href="https://tokbox.com/developer/guides/end-to-end-encryption">end-to-end encryption</a>
     * is set for the session.
     *
     * @return mixed
```

2023-02-22 00:29 UTC, jeffswartz requested changes
Should we rev the version (in Client.php and elsewhere) to 4.12.0?

2023-02-27 15:23 UTC, SecondeJK commented
@jeffswartz I've not bumped the hardcoded version number as #328 will rewrite how this is handled (actually addresses a TODO from 2014 on dynamic user agent string handling)

2023-05-03 15:12 UTC, jeffswartz commented on src/OpenTok/OpenTok.php
> +    *    for the OpenTok session.</li>
```suggestion
    *    for a routed session.</li>
```

2023-05-03 20:02 UTC, jeffswartz reviewed
Please add a commit to rev the minor version.

2023-05-03 20:02 UTC, jeffswartz approved these changes

2023-05-09 14:37 UTC, merged